from __future__ import annotations

from evagix.model import RepoFacts
from evagix.utils import facts_fingerprint


def generated_markdown_header(facts: RepoFacts) -> str:
    fingerprint = facts_fingerprint(facts.to_dict())
    return (
        f"<!-- evagix:generated evagix:fingerprint={fingerprint} -->\n"
        "<!-- Do not edit this file directly unless you intentionally want to fork it from evagix. -->\n\n"
    )
