from __future__ import annotations

from textwrap import dedent

from evagix.model import RepoFacts
from evagix.rendering.fingerprints import generated_markdown_header
from evagix.rendering.sections import _main_body, _shared_sections


def render_agents_md(facts: RepoFacts) -> str:
    return generated_markdown_header(facts) + _main_body(facts, title="AI Agent Instructions")


def render_claude_md(facts: RepoFacts) -> str:
    intro = dedent(
        """
        # Claude Code Instructions

        Follow this repository context before making code changes. Prefer small, reviewable edits and keep
        behavior compatible with the existing architecture.
        """
    ).strip()
    return generated_markdown_header(facts) + intro + "\n\n" + _shared_sections(facts)


def render_gemini_md(facts: RepoFacts) -> str:
    intro = dedent(
        """
        # Gemini CLI Instructions

        Use this repository context before making code changes. Keep changes small, validated, and consistent with the detected project architecture.
        """
    ).strip()
    return generated_markdown_header(facts) + intro + "\n\n" + _shared_sections(facts)


def render_cursor_rule(facts: RepoFacts) -> str:
    frontmatter = dedent(
        """
        ---
        description: Repository-specific coding agent instructions generated by Evagix.
        globs: ["**/*"]
        alwaysApply: true
        ---
        """
    ).strip()
    return generated_markdown_header(facts) + frontmatter + "\n\n" + _main_body(facts, title="Cursor Project Rule")


def render_windsurf_rule(facts: RepoFacts) -> str:
    intro = dedent(
        """
        # Windsurf Project Rule

        Follow these repository-specific rules when editing, reviewing, or generating code in this project.
        """
    ).strip()
    return generated_markdown_header(facts) + intro + "\n\n" + _shared_sections(facts)


def render_copilot_instructions(facts: RepoFacts) -> str:
    intro = dedent(
        """
        # GitHub Copilot Instructions

        Use these instructions for suggestions, edits, and reviews in this repository.
        """
    ).strip()
    return generated_markdown_header(facts) + intro + "\n\n" + _shared_sections(facts)


def render_continue_rule(facts: RepoFacts) -> str:
    intro = dedent(
        """
        # Continue Agent Rule

        Use this local-first repository context before editing, generating, or reviewing code with Continue.
        """
    ).strip()
    return generated_markdown_header(facts) + intro + "\n\n" + _shared_sections(facts)


def render_cline_rule(facts: RepoFacts) -> str:
    intro = dedent(
        """
        # Cline Project Rules

        Follow this repository context before editing, generating, or reviewing code with Cline.
        Keep changes small, evidence-backed, and aligned with the detected validation commands.
        """
    ).strip()
    return generated_markdown_header(facts) + intro + "\n\n" + _shared_sections(facts)


def render_roo_rule(facts: RepoFacts) -> str:
    intro = dedent(
        """
        # Roo Code Project Rules

        Use these repository-specific rules before making code changes with Roo Code.
        Treat generated context as controlled output and avoid behavior-changing edits without validation.
        """
    ).strip()
    return generated_markdown_header(facts) + intro + "\n\n" + _shared_sections(facts)


def render_aider_conventions(facts: RepoFacts) -> str:
    intro = dedent(
        """
        # Aider Conventions

        Load this file with `/read CONVENTIONS.md` or configure it in `.aider.conf.yml` before editing with Aider.
        It is generated from the same governed Evagix repository context as the tool-specific adapters.
        """
    ).strip()
    return generated_markdown_header(facts) + intro + "\n\n" + _shared_sections(facts)


def render_openhands_skill(facts: RepoFacts) -> str:
    intro = dedent(
        """
        # OpenHands Repository Skill

        Use this repository-specific skill before planning, editing, reviewing, or validating changes with OpenHands.
        It is generated from Evagix's governed repository context and should be treated as controlled output.
        """
    ).strip()
    return generated_markdown_header(facts) + intro + "\n\n" + _shared_sections(facts)


def render_generic_agent_context(facts: RepoFacts) -> str:
    intro = dedent(
        """
        # Generic Evagix

        Portable repository context for custom AI coding agents, local LLM workflows, and reviewer prompts.
        """
    ).strip()
    return generated_markdown_header(facts) + intro + "\n\n" + _shared_sections(facts)
